version: '3.8'

services:
  # --- MLFLOW SERVER ---
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow_data:/mlflow # Verileri kaybetmemek için
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
    networks:
      - mlsecops-net

  # --- JENKINS SERVER ---
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    user: root # Docker içinde Docker çalıştırmak için root yetkisi gerekebilir (Lab ortamı için)
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Jenkins'in host docker'ı kullanabilmesi için kritik!
    networks:
      - mlsecops-net
    depends_on:
      - mlflow

networks:
  mlsecops-net:
    driver: bridge